### ISSUE TITLE
Support for hot code reloading?

### ISSUE THREAD

**Issue by tomekw** [kwrooijen/exrm_docker#2]
Hello @kwrooijen! Thank you for this plugin!

I would like to ask a question - is it possible to perform a hot code reloading on new release or Docker in general isn't a good fit for that?

**Comment by kwrooijen** [comment]
Hi @tomekw 

Depends if you mean generating a new Docker release in production or Erlang release and reloading in a running docker container in developerment.

In the first case probably not possible (and not desired?) since creating a new docker release means deploying a new container, not maintaining one and keeping it alive. 

In the case of development when generating a new release and adding it to a running docker container, that should be possible. However it's probably not possible (without hacks, at least) currently with exrm_docker. You'd probably want to generate the release, and add it as a volume (-v) to your docker container. Then whenever you generate a new release and the beam files change, it should be picked up by Docker (since it's a volume) and you can reload them.

Though doing this doesn't seem very productive to me, since you'd have to keep generating a new release over and over. A release only serves the purpose of creating a portable Erlang project, so you might as well continuously test it normally and test the release last. 

Instead you could add the entire project in a Docker container as a volume and let it run with iex for example. That way you won't have to generate a new release every time just for testing and you won't be dependent on exrm_docker.

I hope that answers your question, I'm not really an expert on Docker so I might be wrong on some points, but I believe that's how it is.

**Comment by kwrooijen** [comment]
Closing this issue for now, if you have any other questions feel free to open a new issue.
