### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by simonedamico** [kwrooijen/exrm_docker#3]
Would be great to support Mac and allow the compiling to take place inside a linux docker image.

**Comment by kwrooijen** [comment]
I'd be up for adding Mac support. However I don't own a Mac nor do I have any knowledge of an OSX / Docker setup. So for this to get fixed I'll need some assistance.

**Comment by simonedamico** [comment]
Happy to help. Docker recently release a native version of the app, so actually there is no difference at all between linux and mac docker from outside.
I'm still quite new to the elixir scene and I guess this plugin needs to target all sort of elixir use cases and not just phoenix app, right?

**Comment by kwrooijen** [comment]
> I'm still quite new to the elixir scene and I guess this plugin needs to target all sort of elixir use cases and not just phoenix app, right?

Yes, exrm is a generic elixir tool and isn't specifically targeted for Phoenix. However since Phoenix is actually just a dependency of your Elixir app it should work properly.

> Docker recently release a native version of the app, so actually there is no difference at all between linux and mac docker from outside.

Since Docker is the same on the outside this plugin should work. However if you mean that you want `exrm` (not `exrm_docker`) to generate the release inside a docker container that will be very difficult. Because `exrm` is responsible for generating the release, which it just does on the host machine. All that `exrm_docker` does is copy that release into a docker container and [create an image based on a customizable Dockerfile](https://github.com/kwrooijen/exrm_docker/blob/709604d197733b9f585c97c31d944cd8c2781f87/lib/exrm_docker.ex#L25).

**Comment by kwrooijen** [comment]
Closing this issue for now, if you have any other questions feel free to open a new issue.
