### ISSUE TITLE
Default startup argument for the image

### ISSUE THREAD

**Issue by wmeints** [kwrooijen/exrm_docker#4]
Hi, I'm missing an option for a docker image using this plugin. If you want to use the resulting image with docker-compose you need to specify startup arguments, which I find quite annoying since I use docker-compose.

Docker-compose doesn't support specifying startup arguments for the container as far as I know. So I want to be able to specify commands like console/foreground in advance.

**Comment by kwrooijen** [comment]
Hi @wmeints 

If I understand correctly your problem is that you can't give the argument "console" or "foreground" to your docker-compose setup.
What you could do is add the following line in your config.exs to change the default ENTRYPOINT in the generated Dockerfile (replacing my_app with your application name)

``` Elixir
config :exrm_docker,
  entrypoint: "ENTRYPOINT /opt/rel/my_app/bin/my_app console"
```

This way instead of supplying the `console` argument, it will instead always use it. After setting up your docker-compose.yml you can run `docker-compose run` to get an interactive shell. Note that `docker-compose up` will not work since it does not work with interactive images.

A nicer solution would be to have an extra config option which is the binary argument, however we currently do not support that. If however this is actually your problem I'll be happy to add this option. Otherwise please clarify your issue.

**Comment by wmeints** [comment]
Hi @kwrooijen,

The entrypoint modification does help me with my problem. Thanks for pointing me in the right direction. 

It would indeed be nicer to specify the binary argument separately. This way you don't have to fiddle with the entrypoint. But I can manage for now :-)

**Comment by kwrooijen** [comment]
Hi @wmeints 

Just made a change to the library by adding a `entrypoint_args` option. Simply update to `~> 0.2.0` and add the following to your config:

```
config :exrm_docker,
  entrypoint_args: "console"
```

If you could confirm that this solves your problem then please let me know so I can close this ticket.

**Comment by wmeints** [comment]
Looks like it breaks right now: 

```
docker: Error response from daemon: Container command '/rel/hackatron/bin/hackatron console' not found or does not exist..
```

The release process itself is okay. But the resulting container isn't working properly.
For reference here's the output docker produces:

```
Sending build context to Docker daemon 60.01 MB
Step 1 : FROM centos
 ---> 50dae1ee8677
Step 2 : MAINTAINER Willem Meints
 ---> Using cache
 ---> 74403bf0e27d
Step 3 : COPY rel /rel
 ---> 70153d654906
Removing intermediate container 1837036cedee
Step 4 : ENTRYPOINT /rel/hackatron/bin/hackatron console
 ---> Running in b324d66db181
 ---> fed0fd27abb4
Removing intermediate container b324d66db181
Successfully built fed0fd27abb4
==> The release for hackatron-0.0.1 is ready!
==> You can boot a console running your release with `$ rel/hackatron/bin/hackatron console`
```

**Comment by kwrooijen** [comment]
Sorry about that, made a small mistake with the ENTRYPOINT syntax. Should've read the documentation on that. Made a new patch `0.2.1`, try it out.

**Comment by wmeints** [comment]
It works, thanks for the help!
